name: Author Detector
description: Add label for core team and community members
inputs:
  token:
    description: GitHub token with issue, comment, and label read/write permissions
    default: ${{ github.token }}
  coreLabel:
    description: Label name for core authors
    default: 'core team'
  addCoreLabel:
    description: Label for for core authors?
    default: "true"
  communityLabel:
    description: Label name for community authors
    default: 'community contribution'
  addCommunityLabel:
    description: Label for community authors?
    default: "true"
runs:
  using: 'node16'
  main: 'index.js'
